config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import register
from notes.views import index
from django.conf import settings

urlpatterns = [
    path("", index, name="index"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", register, name="register"),
    path("note/", include("notes.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.ADMIN_ENABLED: urlpatterns.append(path('admin/', admin.site.urls))

notes/urls.py
from django.urls import path

from . import views

app_name = "notes"
urlpatterns = [
    # ex: /note/new/
    path("new/", views.create, name="create"),
    # ex: /note/06bc031d-eb6f-496a-a65a-89b012580365/
    path("<uuid:note_id>/", views.detail, name="detail"),
    # ex: /note/delete/06bc031d-eb6f-496a-a65a-89b012580365/
    # You can use "?ref=" for referral to where the note was deleted
    # ex: /note/delete/06bc031d-eb6f-496a-a65a-89b012580365/?ref=/
    path("<uuid:note_id>/delete", views.delete, name="delete"),
]

notes/models.py
from django.db import models
import uuid
from django.conf import settings
from django.utils import timezone

# Create your models here.
class Note(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    content = models.TextField(blank=True)
    created = models.DateTimeField("Date created", blank=True)
    updated = models.DateTimeField("Date updated", blank=True, null=True)

    def __str__(self):
        '''Object representation'''
        return (self.user.username + ":" + (self.title if self.title != "" else "untitled"))
    
    def save(self, *args, **kwargs):
        '''On save, update timestamps'''
        if not self._state.adding:
            self.updated = timezone.now()
        else:
            self.created = timezone.now()
        return super(Note, self).save(*args, **kwargs)

users/models.py
from django.db import models

# Create your models here.

notes/forms.py
from django import forms

from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["title", "content"]

# New form for default readonly attribute
class DetailNoteForm(NoteForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields["title"].widget.attrs["readonly"] = True
       self.fields["content"].widget.attrs["readonly"] = True

users/forms.py
from django.contrib.auth.forms import UserCreationForm, BaseUserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
        help_text="Required. Must be a valid email address.",
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    # Override form error password2 -> password1
    def _post_clean(self):
        # Use the BaseUserCreationForm (UserCreationForm parent) super()._post_clean() 
        # to override UserCreationForm throughly in Django 4.2
        super(BaseUserCreationForm, self)._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password1")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password1", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

notes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .decorators import user_required
from .models import Note
from django.db.models.functions import Coalesce
from .forms import NoteForm, DetailNoteForm
import requests
from .utils import html_text_to_json
from config.settings import GSS_CHECKER, LANGUAGETOOL_API_URL

def _gss_result_to_array(result):
    arr = []
    matches = result["matches"]
    for error in matches:
        err = {}

        # Context for finding the error text
        context = error["context"]
        context_text = context["text"]
        context_length = context["length"]
        context_offset = context["offset"]

        err["message"] = error["message"]
        err["offset"] = error["offset"]
        err["length"] = error["length"]
        err["text"] = context_text[context_offset:(context_offset + context_length)]
        err["replacement"] = error["replacements"][0]["value"]

        arr.append(err)
    return arr

@login_required
def index(request):
    user_id = request.user.id
    # Search parameter, default "" if parameter not provided (will return all notes)
    search = request.GET.get("search", "")
    # Get notes owned by user in session, ordered by updated date first, and created date if it is null (newly created)
    note_list = Note.objects.filter(user_id=user_id, title__contains=search).order_by(Coalesce("updated", "created").desc())
    return render(request, "index.html", {"note_list": note_list})

@login_required
@user_required
def detail(request, note_id):
    data = {
        "note_id": note_id
    }
    note = Note.objects.get(pk=note_id)
    if request.method == "POST":
        form = DetailNoteForm(request.POST, instance=note)
        if form.is_valid():
            note = form.save()
            # Checking grammar, spelling, & style error with LanguageTool API
            if GSS_CHECKER and (LANGUAGETOOL_API_URL is not None) and request.POST.get("gss-checker"):
                data_json = html_text_to_json(form.cleaned_data["content"])
                params = {"data": data_json, "language": "en-US"}
                # result = requests.post("https://api.languagetoolplus.com/v2/check", params=params)
                result = requests.post(LANGUAGETOOL_API_URL, params=params)
                data["gss_errors"] = _gss_result_to_array(result.json())
    else:
        form = DetailNoteForm(instance=note)
    return render(request, "notes/detail.html", {"form": form, "data": data, "GSS_CHECKER": GSS_CHECKER})

@login_required
def create(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            return redirect("notes:detail", note_id=note.id)
    else:
        form = NoteForm()
    return render(request, "notes/create.html", {"form": form})

@login_required
@user_required
def delete(request, note_id):
    note = Note.objects.get(pk=note_id)
    note.delete()
    ref = request.GET.get("ref", "/")
    return redirect(ref)

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from .decorators import redirect_authenticated_user

# Create your views here.
@redirect_authenticated_user
def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("/")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})

templates/footer.html
<footer class="bg-white dark:bg-gray-900">
    <div class="w-full mx-auto max-w-screen-xl md:flex md:items-center md:justify-center">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 - <a
                href="{% url 'index' %}" class="hover:underline">Pena</a>
        </span>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="flex flex-col min-h-screen bg-white dark:bg-gray-900 p-5">
        {% include "navbar.html" %}
        {% if note_list %}
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 content-start flex-1 my-5">
            {% for note in note_list %}
                <form class="relative group" method="post" action="{% url 'notes:delete' note.id %}?ref={{ request.get_full_path }}" tabindex="0">
                    {% csrf_token %}
                    <div class="flex flex-col h-16 border border-gray-300 dark:border-gray-800">
                        <p class="text-xs font-bold uppercase text-center bg-gray-200 text-gray-900 dark:bg-gray-800 dark:text-gray-200 py-1">Note</p>
                        <a href="{% url 'notes:detail' note.id %}" tabindex="-1" class="h-full bg-gray-50 dark:bg-gray-700 px-2.5 py-2 group-hover:border-b-blue-500 group-hover:border-b-4">
                            <p class="note-title text-sm font-medium truncate text-gray-900  dark:text-gray-300">{% if note.title != "" %} {{ note.title}} {% else %} Untitled {% endif %}</p>
                        </a>
                        <div id="tooltip-{{ forloop.counter0 }}" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:text-gray-900 dark:bg-white">
                            {% if note.title != "" %} {{ note.title}} {% else %} Untitled {% endif %}
                            <div class="tooltip-arrow" data-popper-arrow></div>
                        </div>
                    </div>
                    <button type="submit" tabindex="-1" class="absolute -top-2 -end-2 text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 rounded-full p-1.5 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 hidden group-hover:block group-focus:block">
                        <svg class="w-2 h-2 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                    </button>
                </form>
            {% endfor %}
            </div> 
        {% else %}
            <div class="flex-1 my-5">
                <p class="text-base text-center font-normal text-gray-900 dark:text-white">There are no notes available, please create a new one!.</p>
            </div>
        {% endif%}
        <a href="{% url 'notes:create' %}" class="fixed bottom-10 right-10 md:bottom-16 md:right-16 xl:bottom-20 xl:right-20 text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 rounded-2xl p-5 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <svg class="w-6 h-6 md:w-8 md:h-8 xl:w-10 xl:h-10 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M.188 5H5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707c-.358.362-.617.81-.753 1.3C.148 5.011.166 5 .188 5ZM14 8a6 6 0 1 0 0 12 6 6 0 0 0 0-12Zm2 7h-1v1a1 1 0 0 1-2 0v-1h-1a1 1 0 0 1 0-2h1v-1a1 1 0 0 1 2 0v1h1a1 1 0 0 1 0 2Z"/>
                <path d="M6 14a7.969 7.969 0 0 1 10-7.737V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H.188A.909.909 0 0 1 0 6.962V18a1.969 1.969 0 0 0 1.933 2h6.793A7.976 7.976 0 0 1 6 14Z"/>
            </svg>
        </a>
        {% include "footer.html" %}
    </div>
{% endblock %}

{% block script_footer %}
    {{ block.super }}
    <script src="{% static 'js/notes.js' %}"></script>
{% endblock%}

templates/notes/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="flex flex-col h-screen bg-white dark:bg-gray-900 p-5">
        {% include "navbar.html" %}
        <form id="form-editor" class="flex-1 flex justify-center my-5 overflow-auto" method="post" action="{% url 'notes:create' %}">
            {% csrf_token %}
            <div class="relative md:basis-3/4 flex flex-col w-full border-2 border-gray-400 dark:border-gray-600">
                <input type="text" id="id_title" class="text-sm w-full p-2.5 bg-white dark:bg-gray-900 dark:placeholder-gray-400 text-gray-900 dark:text-white border-0 focus:ring-0" name="title" maxlength="200" placeholder="Write your title here...">
                <hr class="h-[1px] bg-gray-300 dark:bg-gray-700 border-0">
                <div id="editor" class="text-sm w-full h-full p-2.5 bg-white dark:bg-gray-900 text-gray-900 dark:text-white border-0 outline-none cursor-text overflow-y-scroll empty:before:content-[attr(placeholder)] empty:before:text-gray-400" contenteditable="true" placeholder="Write your note here..."></div>
                <textarea class="hidden" name="content" id="id_content"></textarea>
                <button type="submit" class="absolute bottom-5 right-5 md:bottom-8 md:right-8 xl:bottom-10 xl:right-10 text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 rounded-2xl p-5 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
                    <svg class="w-6 h-6 md:w-8 md:h-8 xl:w-10 xl:h-10 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 20">
                        <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.98 2.98 0 0 0 .13 5H5Z"/>
                        <path d="M14.066 0H7v5a2 2 0 0 1-2 2H0v11a1.97 1.97 0 0 0 1.934 2h12.132A1.97 1.97 0 0 0 16 18V2a1.97 1.97 0 0 0-1.934-2Zm-2.359 10.707-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L7 12.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                    </svg>
                </button>
            </div>
        </form>
        {% include "footer.html" %}
    </div>
{% endblock %}

{% block script_footer %}
    {{ block.super }}
    <script src="{% static 'js/notes.js' %}"></script>
    <script src="{% static 'js/editor.js' %}"></script>
    <script>
        formEditor.addEventListener("submit", (e) => {
            /* Wrap with element <p> if there's only one element inside of editor
            I don't know why but this is by default, the first element will be raw text
            And not enclosed by <p> element */
            if (editor.childNodes.length === 1) {
                const wrapper = document.createElement("p");

                if (!editor.firstChild.hasChildNodes()) {
                    wrap(editor.firstChild, wrapper);
                }
            }

            content.value = editor.innerHTML;
        });
    </script>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="flex h-screen bg-white dark:bg-gray-900">
    <div class="basis-3/4 h-full hidden md:block">
        <img class="w-full h-full" src="{% static 'img/background.jpg' %}" alt="Login Background">
    </div>
    <div class="md:basis-1/4 flex flex-col w-full h-full p-5 overflow-y-scroll">
        <div class="flex items-center justify-end w-full mb-5">
            <button id="theme-toggle" type="button" class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
                <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
                <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
            </button>  
        </div>  
        <form class="flex flex-col flex-1 justify-center mb-5" method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <h1 class="text-center text-3xl font-medium mb-5 text-gray-900 dark:text-white">Register</h1>
            <div class="mb-2">
                <label for="id_username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your username</label>
                <input type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" name="username" autofocus autocomplete="username" maxlength="150" required id="id_username" value="{{ form.username.value|default_if_none:'' }}">
                {% if form.username.errors %}
                    <span class="inline-block mt-2 text-xs text-red-500 dark:text-red-400">
                        <ul id="username_errorlist" class="list-inside">
                        {% for error in form.username.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                        </ul>
                    </span>
                {% else %}
                    <span id="username_helptext" class="inline-block mt-2 text-xs text-gray-500 dark:text-gray-400">
                        {{ form.username.help_text }}
                    </span>
                {% endif %}
            </div>
            <div class="mb-2">
                <label for="id_email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                <input type="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" name="email" autocomplete="email" maxlength="254" required id="id_email" value="{{ form.email.value|default_if_none:'' }}">
                {% if form.email.errors %}
                    <span class="inline-block mt-2 text-xs text-red-500 dark:text-red-400">
                        <ul id="email_errorlist" class="list-inside">
                        {% for error in form.email.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                        </ul>
                    </span>
                {% else %}
                    <span id="email_helptext" class="inline-block mt-2 text-xs text-gray-500 dark:text-gray-400">
                        {{ form.email.help_text }}
                    </span>
                {% endif %}
            </div>
            <div class="mb-2">
                <label for="id_password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
                <div class="flex border border-gray-300 dark:border-gray-600 rounded-lg focus-within:outline outline-1 focus-within:outline-blue-500 focus-within:border-blue-500 dark:focus-within:outline-blue-500 dark:focus-within:border-blue-500">
                    <input type="password" class="bg-gray-50 border-0 rounded-l-lg text-gray-900 text-sm focus:ring-0 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white" name="password1" autocomplete="new-password" required id="id_password1">
                    <button id="button-password1" type="button" class="bg-gray-50 dark:bg-gray-700 rounded-r-lg outline outline-none p-2" onclick="clickButtonPassword(this);">
                        <svg id="show-password1-icon" class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 14">
                            <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
                                <path d="M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                                <path d="M10 13c4.97 0 9-2.686 9-6s-4.03-6-9-6-9 2.686-9 6 4.03 6 9 6Z"/>
                            </g>
                        </svg>
                        <svg id="hide-password1-icon" class="w-6 h-6 text-gray-500 dark:text-gray-400 hidden" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M1.933 10.909A4.357 4.357 0 0 1 1 9c0-1 4-6 9-6m7.6 3.8A5.068 5.068 0 0 1 19 9c0 1-3 6-9 6-.314 0-.62-.014-.918-.04M2 17 18 1m-5 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                        </svg>
                    </button>
                </div>
                {% if form.password1.errors %}
                        <span class="inline-block mt-2 text-xs text-red-500 dark:text-red-400">
                            <ul id="password1_errorlist" class="list-inside">
                            {% for error in form.password1.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        </span>
                {% else %}
                    <span id="password1_helptext" class="inline-block mt-2 text-xs text-gray-500 dark:text-gray-400">
                        {{ form.password1.help_text }}
                    </span>
                {% endif %}
            </div>
            <div class="mb-2">
                <label for="id_password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password confirmation</label>
                <div class="flex border border-gray-300 dark:border-gray-600 rounded-lg focus-within:outline outline-1 focus-within:outline-blue-500 focus-within:border-blue-500 dark:focus-within:outline-blue-500 dark:focus-within:border-blue-500">
                    <input type="password" class="bg-gray-50 border-0 rounded-l-lg text-gray-900 text-sm focus:ring-0 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white" name="password2" autocomplete="new-password" required id="id_password2">
                    <button id="button-password2" type="button" class="bg-gray-50 dark:bg-gray-700 rounded-r-lg outline outline-none p-2" onclick="clickButtonPassword(this);">
                        <svg id="show-password2-icon" class="w-6 h-6 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 14">
                            <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
                                <path d="M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                                <path d="M10 13c4.97 0 9-2.686 9-6s-4.03-6-9-6-9 2.686-9 6 4.03 6 9 6Z"/>
                            </g>
                        </svg>
                        <svg id="hide-password2-icon" class="w-6 h-6 text-gray-500 dark:text-gray-400 hidden" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M1.933 10.909A4.357 4.357 0 0 1 1 9c0-1 4-6 9-6m7.6 3.8A5.068 5.068 0 0 1 19 9c0 1-3 6-9 6-.314 0-.62-.014-.918-.04M2 17 18 1m-5 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                        </svg>
                    </button>
                </div>
                {% if form.password2.errors %}
                    <span class="inline-block mt-2 text-xs text-red-500 dark:text-red-400">
                        <ul id="password2_errorlist" class="list-inside">
                        {% for error in form.password2.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                        </ul>
                    </span>
                {% else %}
                    <span id="password2_helptext" class="inline-block mt-2 text-xs text-gray-500 dark:text-gray-400">
                        {{ form.password2.help_text }}
                    </span>
                {% endif %}
            </div>
            <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full md:w-24 mb-2 px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Register</button>
            <input type="hidden" name="next" value="{{ next }}">
            <p class="text-sm font-medium text-gray-900 dark:text-white">Have an account? login <a href="{% url 'login' %}">here!</a></p>
        </form>
        {% include "footer.html" %}
    </div>
</div>
{% endblock %}

{% block script_footer %}
    {{ block.super }}
    <script src="{% static 'js/form.js' %}"></script>
    {% if not form.password1.errors %}
    <script>
        // can't iterate trough help_text from django template (it generated like a string not a list)
        // so i write this to make the class of list (or string) generated customizable by tailwind css
        document.querySelectorAll("#password1_helptext ul")[0].classList.add("list-disc", "list-inside");
    </script>
    {% endif %}
    {% if form.errors %}
    <script>
        // can't find how to determine if variable an iterable or not in django template
        // or maybe form.field.errors is not iterable by default
        // i write this to check if form.field.errors only have 1 error or not
        var errorList = ["username_errorlist", "email_errorlist", "password1_errorlist", "password2_errorlist"]

        errorList.forEach(function(elementId) {
            const element = document.getElementById(elementId);
            const elementList = element.getElementsByTagName("li");

            if (element !== null && elementList.length > 1) element.classList.add("list-disc")
        });
    </script>
    {% endif %}
{% endblock %}